### ISSUE TITLE
MMR graph does not distinguish between Knockout and Standard MMR

### ISSUE THREAD

**Issue by jtaylor1022** [Fortify-Labs/Fortify#177]
**Describe the bug**
Not sure if this is a bug or a feature request, but the MMR graph does not make a distinction between Knockout and Standard MMR. This can create a graph where the MMR value seems to rise and fall dramatically when playing the two game types if the player has drastically different MMR values for each type.

**To Reproduce**
Play Standard and Knockout ranked games while being Lord level in one and non-Lord level in another.

**Expected behavior**
Maybe separate lines for Knockout and Standard MMR?

**Screenshots**
<img width="958" alt="Screen Shot 2020-08-22 at 2 10 58 PM" src="https://user-images.githubusercontent.com/15912478/90965976-40aa3780-e482-11ea-8d7c-a5a52d1511c1.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version 13.1.2
(don't think this really matters though)

**Smartphone (please complete the following information):**
N/A

**Additional context**
Great work so far!

**Comment by ThomasK33** [comment]
I'll change it to display standard for now and then create a toggle to select between the different game modes.

**Comment by ThomasK33** [comment]
So fixing this might actually kill the mmr recording for non-lords for now.

While it's true that I forgot to set the match type in the rank update event, we do not get any match type / match mode information from the game via gsi.

We're currently trying to duct tape a match mode together which may or may not work.

I'm going to take a look at how many users are affected by this bug and will probably deactivate the non-lord rank recording.


If you could send me your steamid on either discord or other ways, I'd write a small script and delete the wrongly assigned data points.
