### ISSUE TITLE
Old lord MMR shown for current non-lords after reset

### ISSUE THREAD

**Issue by Amorian** [Fortify-Labs/Fortify#203]
MMR shown on Fortify's Webpage still shows the old lord MMR, when ranks are shown accurately. This seems to be a problem only on the website, the average MMR shown and the MMR on the bot responses works as intended.

This lobby should give a good idea of the issue - https://fortify.gg/lobby/117367314

**Comment by ThomasK33** [comment]
Now, with proper game mode detection, the rank tier progression tracking should work for all non-lords for Standard and Turbo.

For the next rank reset, only a rank clear for all MMR values and rank_tiers will be required to properly reset ranks in Fortify.

Historical rank data is tracked in influxdb and thus not effected by changes in the postgres db.
